# (name, location, state) -- candidates for discover_mosques.py, sourced from
# the "100 Iconic, Famous and Historically Significant Mosques in Malaysia"
# directory, filtered to entries not already present in seed_data.MOSQUES.
MOSQUES_TO_ADD = [
    ("As Syakirin Mosque", "KLCC", "Kuala Lumpur"),
    ("Al-Rahman Mosque", "Kuala Lumpur", "Kuala Lumpur"),
    ("Abdul Rahman Auf Mosque", "Kuala Lumpur", "Kuala Lumpur"),
    ("Al-Bukhari Foundation Mosque", "Kuala Lumpur", "Kuala Lumpur"),
    ("Saidina Abu Bakar As Siddiq Mosque", "Kuala Lumpur", "Kuala Lumpur"),
    ("An-Nur Jamek Mosque", "Victoria, Labuan", "Labuan"),
    ("Pasir Pelangi Royal Mosque", "Johor Bahru", "Johor"),
    ("Sultan Ibrahim Jamek Mosque", "Muar", "Johor"),
    ("Bandar Baru UDA Jamek Mosque", "Johor Bahru", "Johor"),
    ("Masjid Bandar Kota Tinggi", "Kota Tinggi", "Johor"),
    ("Masjid Al-Husna Bandar Tenggara", "Bandar Tenggara", "Johor"),
    ("Masjid Sultan Ismail, Tanjung Agas", "Tangkak", "Johor"),
    ("Albukhary Mosque", "Alor Setar", "Kedah"),
    ("Masjid Sultan Abdul Halim Muadzam Shah", "Pokok Sena", "Kedah"),
    ("Sultan Ismail Petra Mosque", "Rantau Panjang", "Kelantan"),
    ("Jubli Perak Sultan Ismail Petra Mosque", "Rantau Panjang", "Kelantan"),
    ("Masjid Jamek Razaleigh", "Gua Musang", "Kelantan"),
    ("Masjid Tengku Razaleigh", "Gua Musang", "Kelantan"),
    ("Masjid Al-Ismaili", "Pasir Pekan, Tumpat", "Kelantan"),
    ("Masjid Bandar Jeli", "Jeli", "Kelantan"),
    ("Masjid Bandar Pasir Mas", "Pasir Mas", "Kelantan"),
    ("Abidin Mosque", "Kuala Terengganu", "Terengganu"),
    ("Al-Muktafi Billah Shah Mosque", "Kuala Terengganu", "Terengganu"),
    ("Masjid Lapan Kubah", "Besut", "Terengganu"),
    ("Masjid Rusila", "Marang", "Terengganu"),
    ("Masjid Ulul Albab", "Besut", "Terengganu"),
    ("Sultan Abdullah Mosque", "Pekan", "Pahang"),
    ("Sultan Mahmud Mosque", "Kuala Lipis", "Pahang"),
    ("Mohamed Noah Foundation Mosque", "Genting Highlands, Bentong", "Pahang"),
    ("Tengku Ampuan Afzan Mosque", "Kuantan", "Pahang"),
    ("Tengku Hassanal Ibrahim Alam Shah Mosque", "Temerloh Jaya", "Pahang"),
    ("Perlis State Mosque", "Arau", "Perlis"),
    ("Alwi Mosque", "Kangar", "Perlis"),
    ("Masjid Putra Simpang Empat", "Simpang Empat", "Perlis"),
    ("Acheen Street Mosque", "George Town", "Penang"),
    ("Butterworth Floating Mosque", "Butterworth", "Penang"),
    ("Batu Uban Jamek Mosque", "Gelugor, Batu Uban", "Penang"),
    ("Masjid Al-Malik Khalid USM", "Universiti Sains Malaysia, Penang", "Penang"),
    ("Masjid Jamek Hashim Yahaya", "George Town", "Penang"),
    ("Masjid Benggali Lebuh Leith", "George Town", "Penang"),
    ("Panglima Kinta Mosque", "Ipoh", "Perak"),
    ("Town Padang Mosque", "Ipoh", "Perak"),
    ("Paloh Street Mosque", "Ipoh", "Perak"),
    ("Muhammadiah Mosque", "Ipoh", "Perak"),
    ("Gopeng Baru Jamek Mosque", "Gopeng", "Perak"),
    ("Al-Khairiah Mosque", "Pangkor Island", "Perak"),
    ("Puncak Alam Mosque", "Puncak Alam", "Selangor"),
    ("Sultan Abdul Samad Mosque KLIA", "Sepang", "Selangor"),
    ("As-Salam Mosque", "Puchong Perdana", "Selangor"),
    ("Tengku Ampuan Jemaah Mosque", "Bukit Jelutong", "Selangor"),
    ("Raja Haji Fi Sabilillah Mosque", "Cyberjaya", "Selangor"),
    ("Ara Damansara Mosque", "Petaling Jaya", "Selangor"),
    ("Jamek Ar-Rahimah Mosque", "Hulu Selangor", "Selangor"),
    ("Sultan Alaeddin Royal Mosque", "Jugra", "Selangor"),
    ("Negeri Sembilan State Mosque", "Seremban", "Negeri Sembilan"),
    ("Seremban Jamek Mosque", "Seremban", "Negeri Sembilan"),
    ("Malacca Straits Mosque", "Pulau Melaka, Banda Hilir", "Melaka"),
    ("Malacca Chinese Mosque", "Krubong", "Melaka"),
    ("Bukit Cina Mosque", "Melaka City", "Melaka"),
    ("Peringgit Mosque", "Peringgit", "Melaka"),
    ("Pengkalan Rama Fathur Rahman Mosque", "Pengkalan Rama", "Melaka"),
    ("Sabah State Mosque", "Kota Kinabalu", "Sabah"),
    ("Al-Kauthar Mosque", "Tawau", "Sabah"),
    ("Sandakan Jamek Mosque", "Sandakan", "Sabah"),
    ("Sandakan District Mosque", "Sandakan", "Sabah"),
    ("Masjid Raya Kota Belud", "Kota Belud", "Sabah"),
    ("Masjid Raya Ranau", "Ranau", "Sabah"),
    ("Al-Qadim Mosque", "Sibu", "Sarawak"),
    ("Indian Mosque Kuching", "Kuching", "Sarawak"),
    ("Old Sarawak State Mosque", "Kuching", "Sarawak"),
]
